"""
CapCoach - Decision Tree Training & Export
Week 2 deliverable for Member 3 (ML Engineer)

Pipeline:
  1. Load the synthetic dataset from Week 1
  2. Train/test split (800/200)
  3. Train a Scikit-Learn Decision Tree
  4. Evaluate with a Confusion Matrix + classification report
  5. Print the learned tree rules (glass-box proof for judges)
  6. Export the tree as a drop-in Java class (no TFLite / LiteRT runtime needed)

Requires only: pandas, numpy, scikit-learn.
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

FEATURES = [
    "Recovery_Debt_Score",
    "Days_Until_Due",
    "Task_Priority_Weight",
    "Is_Fixed_Time",
    "Is_Recovery_Activity",
    "Duration_Minutes",
]

# ---------------------------------------------------------------- 1. Load
# The Android package this class will live in. MUST match the folder path
# under app/src/main/java/ exactly, or the file will not compile.
JAVA_PACKAGE = "com.example.codenection2026.engine"

MAX_DEPTH = 7   # minimum depth at which all six features contribute

df = pd.read_csv("capcoach_synthetic_tasks.csv")
X = df[FEATURES]
y = df["Label"]

# ---------------------------------------------------------------- 2. Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=600, random_state=42, stratify=y
)
print(f"Train rows: {len(X_train)}   Test rows: {len(X_test)}")

# ---------------------------------------------------------------- 3. Train
# max_depth is capped so the tree stays small, readable, and fast on-device.
clf = DecisionTreeClassifier(max_depth=MAX_DEPTH, random_state=42)
clf.fit(X_train, y_train)

# ---------------------------------------------------------------- 4. Evaluate
y_pred = clf.predict(X_test)

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion Matrix")
print("                 Predicted MOVE   Predicted KEEP")
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
print(f"Actual MOVE          {cm[0][0]:>6}          {cm[0][1]:>6}")
print(f"Actual KEEP          {cm[1][0]:>6}          {cm[1][1]:>6}")

print("\nClassification Report")
print(classification_report(y_test, y_pred, target_names=["MOVE (0)", "KEEP (1)"]))

# The safety check that matters for the pitch:
fixed_tasks = X_test[X_test["Is_Fixed_Time"] == 1]
if len(fixed_tasks) > 0:
    fixed_preds = clf.predict(fixed_tasks)
    print(f"SAFETY CHECK - fixed-time tasks in test set: {len(fixed_tasks)}")
    print(f"  Predicted KEEP: {int(fixed_preds.sum())} / {len(fixed_tasks)}")
    print("  (Must be 100% - the model should never tell a student to skip a shift or exam.)")

# ---------------------------------------------------------------- 5. Tree rules
print("\nLearned tree (glass-box - show this to judges):")
print(export_text(clf, feature_names=FEATURES))

print("Feature importances:")
for name, imp in sorted(zip(FEATURES, clf.feature_importances_), key=lambda t: -t[1]):
    print(f"  {name:<24} {imp:.4f}")


# ------------------------------------------------- 6. PATH A: export to Java
def tree_to_java(tree_clf, feature_names, accuracy, n_train, n_test):
    """Convert the trained tree into a complete, drop-in Java class."""
    t = tree_clf.tree_
    lines = []
    lines.append(f"package {JAVA_PACKAGE};")
    lines.append("")
    lines.append("/**")
    lines.append(" * LoadShedder - CapCoach's on-device task triage model.")
    lines.append(" *")
    lines.append(" * AUTO-GENERATED by train_decision_tree.py. Do not hand-edit:")
    lines.append(" * retrain and regenerate instead, or the model and the code drift apart.")
    lines.append(" *")
    lines.append(f" * Source model : Scikit-Learn DecisionTreeClassifier (max_depth={MAX_DEPTH})")
    lines.append(f" * Trained on   : {n_train} rows | Tested on {n_test} rows")
    lines.append(f" * Test accuracy: {accuracy:.4f}")
    lines.append(" *")
    lines.append(" * The tree is exported as plain branching logic rather than a .tflite")
    lines.append(" * binary: identical decisions, no runtime dependency, nothing to load")
    lines.append(" * from assets, and every branch is auditable in source.")
    lines.append(" */")
    lines.append("public final class LoadShedder {")
    lines.append("")
    lines.append("    /** Task should stay where it is. */")
    lines.append("    public static final int KEEP = 1;")
    lines.append("")
    lines.append("    /** Task is safe to postpone - offer it in the rebalance dialog. */")
    lines.append("    public static final int MOVE = 0;")
    lines.append("")

    lines.append("    private LoadShedder() {")
    lines.append("        // Static utility class - not instantiable.")
    lines.append("    }")
    lines.append("")
    lines.append("    /**")
    lines.append("     * Decide whether a single task should be kept or moved.")
    lines.append("     *")
    lines.append("     * @param recoveryDebtScore  0-100, from CapacityCalculator")
    lines.append("     * @param daysUntilDue       whole days until the deadline")
    lines.append("     * @param taskPriorityWeight 3 High, 2 Medium, 1 Low - set by the user")
    lines.append("     *                           per task, independent of category")
    lines.append("     * @param isFixedTime        1 if immovable (shift, exam, class), else 0")
    lines.append("     * @param isRecoveryActivity 1 if the category is tagged as recovery")
    lines.append("     *                           (Social today), else 0")
    lines.append("     * @param durationMinutes    task length in minutes")
    lines.append("     * @return {@link #KEEP} or {@link #MOVE}")
    lines.append("     */")
    lines.append("    public static int predictTaskAction(")
    lines.append("            int recoveryDebtScore,")
    lines.append("            int daysUntilDue,")
    lines.append("            int taskPriorityWeight,")
    lines.append("            int isFixedTime,")
    lines.append("            int isRecoveryActivity,")
    lines.append("            int durationMinutes) {")

    java_names = {
        "Recovery_Debt_Score": "recoveryDebtScore",
        "Days_Until_Due": "daysUntilDue",
        "Task_Priority_Weight": "taskPriorityWeight",
        "Is_Fixed_Time": "isFixedTime",
        "Is_Recovery_Activity": "isRecoveryActivity",
        "Duration_Minutes": "durationMinutes",
    }

    # Hard safety rails, independent of whatever the tree learned.
    lines.append("")
    lines.append("        // Rail 1: an immovable commitment is never surrendered,")
    lines.append("        // regardless of what the learned branches below would say.")
    lines.append("        if (isFixedTime == 1) {")
    lines.append("            return KEEP;")
    lines.append("        }")
    lines.append("")
    lines.append("        // Rail 2: recovery activities are a protective buffer, not")
    lines.append("        // load. Social support is negatively correlated with burnout,")
    lines.append("        // so isolating an already-exhausted student would make things")
    lines.append("        // worse. Never shed recovery time under heavy debt.")
    lines.append("        //")
    lines.append("        // This checks a FLAG, not a category id, so tagging Fitness or")
    lines.append("        // Meditation as recovery later needs only a database change.")
    lines.append("        if (isRecoveryActivity == 1 && recoveryDebtScore > 80) {")
    lines.append("            return KEEP;")
    lines.append("        }")
    lines.append("")
    lines.append("        // Rail 3: high-priority work that is imminent is protected on")
    lines.append("        // its own merits. Telling a student to postpone something due")
    lines.append("        // tomorrow that they marked High is the worst thing this")
    lines.append("        // engine could do, so it is never left to the learned branches.")
    lines.append("        if (taskPriorityWeight == 3 && daysUntilDue <= 2) {")
    lines.append("            return KEEP;")
    lines.append("        }")
    lines.append("")

    def recurse(node, depth):
        pad = "    " * (depth + 2)
        if t.feature[node] != -2:  # -2 means leaf
            feat = java_names[feature_names[t.feature[node]]]
            thresh = t.threshold[node]
            lines.append(f"{pad}if ({feat} <= {thresh:.4f}) {{")
            recurse(t.children_left[node], depth + 1)
            lines.append(f"{pad}}} else {{")
            recurse(t.children_right[node], depth + 1)
            lines.append(f"{pad}}}")
        else:
            value = t.value[node][0]
            label = int(np.argmax(value))
            word = "KEEP" if label == 1 else "MOVE";
            lines.append(f"{pad}return {word};")

    recurse(0, 0)
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


java_code = tree_to_java(clf, FEATURES, accuracy_score(y_test, y_pred),
                         len(X_train), len(X_test))
with open("LoadShedder.java", "w") as f:
    f.write(java_code)
print("\nPATH A complete -> LoadShedder.java")
print("Copy to: app/src/main/java/" + JAVA_PACKAGE.replace(".", "/") + "/LoadShedder.java")