package com.example.codenection2026_package.engine;

/**
 * LoadShedder - CapCoach's on-device task triage model.
 *
 * AUTO-GENERATED by train_decision_tree.py. Do not hand-edit:
 * retrain and regenerate instead, or the model and the code drift apart.
 *
 * Source model : Scikit-Learn DecisionTreeClassifier (max_depth=7)
 * Trained on   : 2400 rows | Tested on 600 rows
 * Test accuracy: 0.9883
 *
 * The tree is exported as plain branching logic rather than a .tflite
 * binary: identical decisions, no runtime dependency, nothing to load
 * from assets, and every branch is auditable in source.
 */
public final class LoadShedder {

    /** Task should stay where it is. */
    public static final int KEEP = 1;

    /** Task is safe to postpone - offer it in the rebalance dialog. */
    public static final int MOVE = 0;

    private LoadShedder() {
        // Static utility class - not instantiable.
    }

    /**
     * Decide whether a single task should be kept or moved.
     *
     * @param recoveryDebtScore  0-100, from CapacityCalculator
     * @param daysUntilDue       whole days until the deadline
     * @param taskPriorityWeight 3 High, 2 Medium, 1 Low - set by the user
     *                           per task, independent of category
     * @param isFixedTime        1 if immovable (shift, exam, class), else 0
     * @param isRecoveryActivity 1 if the category is tagged as recovery
     *                           (Social today), else 0
     * @param durationMinutes    task length in minutes
     * @return {@link #KEEP} or {@link #MOVE}
     */
    public static int predictTaskAction(
            int recoveryDebtScore,
            int daysUntilDue,
            int taskPriorityWeight,
            int isFixedTime,
            int isRecoveryActivity,
            int durationMinutes) {

        // Rail 1: an immovable commitment is never surrendered,
        // regardless of what the learned branches below would say.
        if (isFixedTime == 1) {
            return KEEP;
        }

        // Rail 2: recovery activities are a protective buffer, not
        // load. Social support is negatively correlated with burnout,
        // so isolating an already-exhausted student would make things
        // worse. Never shed recovery time under heavy debt.
        //
        // This checks a FLAG, not a category id, so tagging Fitness or
        // Meditation as recovery later needs only a database change.
        if (isRecoveryActivity == 1 && recoveryDebtScore > 80) {
            return KEEP;
        }

        // Rail 3: high-priority work that is imminent is protected on
        // its own merits. Telling a student to postpone something due
        // tomorrow that they marked High is the worst thing this
        // engine could do, so it is never left to the learned branches.
        if (taskPriorityWeight == 3 && daysUntilDue <= 2) {
            return KEEP;
        }

        if (recoveryDebtScore <= 60.5000) {
            return KEEP;
        } else {
            if (isFixedTime <= 0.5000) {
                if (daysUntilDue <= 3.5000) {
                    if (recoveryDebtScore <= 80.5000) {
                        return KEEP;
                    } else {
                        if (daysUntilDue <= 2.5000) {
                            if (durationMinutes <= 105.0000) {
                                return KEEP;
                            } else {
                                if (isRecoveryActivity <= 0.5000) {
                                    return MOVE;
                                } else {
                                    return KEEP;
                                }
                            }
                        } else {
                            if (isRecoveryActivity <= 0.5000) {
                                return MOVE;
                            } else {
                                return KEEP;
                            }
                        }
                    }
                } else {
                    if (isRecoveryActivity <= 0.5000) {
                        if (recoveryDebtScore <= 80.5000) {
                            if (taskPriorityWeight <= 1.5000) {
                                if (daysUntilDue <= 5.5000) {
                                    return KEEP;
                                } else {
                                    return MOVE;
                                }
                            } else {
                                if (durationMinutes <= 150.0000) {
                                    return KEEP;
                                } else {
                                    return KEEP;
                                }
                            }
                        } else {
                            return MOVE;
                        }
                    } else {
                        if (recoveryDebtScore <= 79.5000) {
                            if (taskPriorityWeight <= 1.5000) {
                                if (daysUntilDue <= 5.5000) {
                                    return KEEP;
                                } else {
                                    return MOVE;
                                }
                            } else {
                                if (durationMinutes <= 150.0000) {
                                    return KEEP;
                                } else {
                                    return KEEP;
                                }
                            }
                        } else {
                            return KEEP;
                        }
                    }
                }
            } else {
                return KEEP;
            }
        }
    }
}